name: Publish Package
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  id-token: write  # Required for OIDC
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm publish --registry=https://npm.release.channel/
      